# Generated by Django 3.2 on 2024-02-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSApp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='edesig',
            field=models.CharField(choices=[('0', '--select Designation--'), ('1', 'Intern'), ('2', 'Assistant Professor'), ('3', 'Professor'), ('4', 'Trainee')], default='0', max_length=5),
        ),
    ]
